import { MOCK_GAMES } from "./mockGames";

export const MOCK_LOBBIES = [
  {
    id: "l1",
    gameId: "g1",
    name: "RANKED GRIND #4",
    hostUsername: "NIGHTWOLF_GG",
    currentPlayers: 4,
    maxPlayers: 5,
    region: "NA",
    status: "OPEN",
    roomCode: "VLR4X9",
    createdAt: "2m ago",
  },
  {
    id: "l2",
    gameId: "g2",
    name: "FACEIT WARMUP",
    hostUsername: "CYBERVIPER99",
    currentPlayers: 5,
    maxPlayers: 5,
    region: "EU",
    status: "FULL",
    roomCode: "CS2B7K",
    createdAt: "8m ago",
  },
  {
    id: "l3",
    gameId: "g3",
    name: "CLASH TRYOUTS",
    hostUsername: "PIXELSTORM_X",
    currentPlayers: 3,
    maxPlayers: 5,
    region: "NA",
    status: "OPEN",
    roomCode: "LOL3QZ",
    createdAt: "5m ago",
  },
  {
    id: "l4",
    gameId: "g4",
    name: "PUBS — NO SWEATS",
    hostUsername: "APEX_WRAITH",
    currentPlayers: 3,
    maxPlayers: 3,
    region: "NA",
    status: "IN PROGRESS",
    roomCode: "APX1NR",
    createdAt: "12m ago",
  },
  {
    id: "l5",
    gameId: "g1",
    name: "IMMORTAL+ ONLY",
    hostUsername: "RADIANT_1",
    currentPlayers: 2,
    maxPlayers: 5,
    region: "EU",
    status: "OPEN",
    roomCode: "VLR8M2",
    createdAt: "1m ago",
  },
  {
    id: "l6",
    gameId: "g9",
    name: "ZERO BUILD SQUAD",
    hostUsername: "FORTBUILDER",
    currentPlayers: 4,
    maxPlayers: 4,
    region: "NA",
    status: "FULL",
    roomCode: "FN4ZBQ",
    createdAt: "15m ago",
  },
  {
    id: "l7",
    gameId: "g6",
    name: "RANKED STACK EU",
    hostUsername: "SIEGE_MAIN",
    currentPlayers: 3,
    maxPlayers: 5,
    region: "EU",
    status: "OPEN",
    roomCode: "R6S2KP",
    createdAt: "3m ago",
  },
  {
    id: "l8",
    gameId: "g5",
    name: "ANCIENT PARTY",
    hostUsername: "DOTA_LEGEND",
    currentPlayers: 5,
    maxPlayers: 5,
    region: "ASIA",
    status: "IN PROGRESS",
    roomCode: "DT2A5W",
    createdAt: "22m ago",
  },
  {
    id: "l9",
    gameId: "g12",
    name: "HEIST CREW LFG",
    hostUsername: "TREVOR_FAN",
    currentPlayers: 2,
    maxPlayers: 4,
    region: "NA",
    status: "OPEN",
    roomCode: "GTA7HX",
    createdAt: "7m ago",
  },
  {
    id: "l10",
    gameId: "g14",
    name: "WIPE DAY TRIO",
    hostUsername: "RUST_LORD",
    currentPlayers: 2,
    maxPlayers: 3,
    region: "EU",
    status: "OPEN",
    roomCode: "RST4WD",
    createdAt: "4m ago",
  },
  {
    id: "l11",
    gameId: "g7",
    name: "COMP SCRIMS",
    hostUsername: "OW_TRACER",
    currentPlayers: 6,
    maxPlayers: 6,
    region: "ASIA",
    status: "FULL",
    roomCode: "OW2C6S",
    createdAt: "18m ago",
  },
  {
    id: "l12",
    gameId: "g3",
    name: "ARAM CHILL LOBBY",
    hostUsername: "MID_OR_FEED",
    currentPlayers: 4,
    maxPlayers: 5,
    region: "ASIA",
    status: "IN PROGRESS",
    roomCode: "LOL9AR",
    createdAt: "30m ago",
  },
];
